// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
public interface ISocketServer
{
	/// <summary>
	/// Возвращает признак того, доступен ли в данный момент сервер
	/// </summary>
	bool Started { get; }
	
	/// <summary>
	/// Возвращает логический сервер
	/// </summary>
	ILogicServer LogicServer { get; }
	
	/// <summary>
	/// Запускает сервер
	/// </summary>
	void Start();
	
	/// <summary>
	/// Останавливает сервер
	/// </summary>
	void Stop();
	
	/// <summary>
	/// Перезапускает сервер
	/// </summary>
	void Restart();
}

